version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: pg_vel
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pq-vel:/var/lib/postgresql/data

volumes:
  pq-vel: